import Vue from 'vue'
import {
    Container,
    Header,
    Aside,
    Main,
    Button,
    Menu,
    MenuItem,
    Submenu,
    Breadcrumb,
    BreadcrumbItem,
    Form,
    FormItem,
    Table,
    TableColumn,
    Input,
    Icon,
    Pagination,
    DatePicker,
    Radio,
    RadioGroup,
    RadioButton,
    Checkbox,
    CheckboxButton,
    CheckboxGroup,
    InputNumber,
    Loading
  } from 'element-ui'
  
  Vue
    .use(Container)
    .use(Header)
    .use(Aside)
    .use(Main)
    .use(Button)
    .use(Menu)
    .use(MenuItem)
    .use(Submenu)
    .use(Breadcrumb)
    .use(BreadcrumbItem)
    .use(Form)
    .use(FormItem)
    .use(Table)
    .use(TableColumn)
    .use(Input)
    .use(Icon)
    .use(Pagination)
    .use(DatePicker)
    .use(Radio)
    .use(RadioGroup)
    .use(RadioButton)
    .use(Checkbox)
    .use(CheckboxButton)
    .use(CheckboxGroup)
    .use(InputNumber)
    .use(Loading)